### ISSUE TITLE
[Bug]: Placeholder corners not rounded

### ISSUE THREAD

**Issue by hubertdej** [cloudscape-design/board-components#225]
### Browser

Chrome, Firefox

### Package version

3.0.6

### React version

v18.2.0

### Description

# Placeholder corners not rounded

## Problem

When dragging a board item onto the dashboard, placeholders are shown without rounded corners. According to the source code, the placeholders should have the same border radius as the containers. However, the generated CSS style for the placeholders contains `border-radius: var(--border-radius-container-1aveko, 0px);`, while all other references to the container border radius look like `var(--border-radius-container-gh9ysk, 16px);`.

## Expected Behavior

I expected the placeholders to have rounded corners just like the containers.

## Steps to Reproduce

1. Go to the official [demo](https://cloudscape.design/examples/react/configurable-dashboard.html).
2. Drag a Board item onto the dashboard.
3. Observe the placeholders and notice that they do not have rounded corners.

The issue is not limited to the online demo, as it can also be reproduced when using version 3.0.6 of the library locally.

## Troubleshooting Steps

I was able to override the styling locally using a separate .scss file:

```scss
@use '~@cloudscape-design/design-tokens' as cs;

.awsui_placeholder_1h7dk_4221b_1 {
  border-radius: cs.$border-radius-container !important;
}
```

## Screenshots

![screenshot](https://user-images.githubusercontent.com/34969251/228979534-79571ab1-23f0-4b0c-9d7d-c7281414c131.png)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate problems

**Comment by just-boris** [comment]
Thanks for the report. I reproduced the issue and working on a fix

**Comment by hubertdej** [comment]
This may be related to another issue where the placeholders are displaying incorrectly in the dark mode:

![image](https://user-images.githubusercontent.com/34969251/229209619-47234008-8cc1-4f29-ab39-fce77915f3e6.png)

**Comment by just-boris** [comment]
Both issues were fixed in `@cloudscape-design/board-components@3.0.8`. No longer reproducible on our demo
