### ISSUE TITLE
[Bug]: Board breaking in splitted view on an ultrawide screen

### ISSUE THREAD

**Issue by luiz-paino** [cloudscape-design/board-components#243]
### Browser

Chrome, Firefox

### Package version

^3.0.12

### React version

18.2.0

### Description

After using windows shortcuts "Windows + Any Arrow" to the browser window position, when i add a new Widget to an empty board, it break the page, and everything disappear.

![image](https://github.com/cloudscape-design/board-components/assets/66832435/3b8a5750-3065-4231-b203-2616d0381f48)

![image](https://github.com/cloudscape-design/board-components/assets/66832435/58944c58-34e5-471d-b702-01f02448ba21)

The error occurred in a lg flatron 29wk500-p monitor.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate problems

**Comment by pan-kot** [comment]
Hello,

Thank you very much for reporting the issue!

We have managed to reproduce an issue which looks very similar to the one reported and we are working on the mitigation. I will link the PR once ready so that you can track the fix readiness.

**Comment by pan-kot** [comment]
Hello,

The fix has been merged and released. Could you please check if the described bug still persists on your end?

**Comment by luiz-paino** [comment]
I'm testing on version 3.0.20 and the error seems to persist

![image](https://github.com/cloudscape-design/board-components/assets/66832435/5fa18027-f3ef-45c3-9ad5-9281dd5013e8)

**Comment by luiz-paino** [comment]
We did a new test with the updated changes and it seems to works now, i believe it was some cache problem here, thank you!
